teamd: Pass correct parameter type to accept API
accept() expects sockaddr as second parameter

int accept (int, struct sockaddr *__restrict, socklen_t *__restrict);

Fixes build with gcc-16 on musl systems
| ../../git/teamd/teamd_usock.c: In function 'callback_usock':
| ../../git/teamd/teamd_usock.c:280:40: error: passing argument 2 of 'accept' from incompatible pointer type [-Wincompatible-pointer-types]
|   280 |         sock = accept(ctx->usock.sock, &addr, &alen);
|       |                                        ^~~~~
|       |                                        |
|       |                                        struct sockaddr_un *

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Jiri Pirko <jiri@nvidia.com>