teamd: Include missing headers for strrchr and memcmp
Compiler does not see the prototype for these functions otherwise and
build fails e.g.

| ../../git/teamd/teamd_phys_port_check.c:52:10: error: call to undeclared library function 'strrchr' with type 'char *(const char *, int)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
|         start = strrchr(link, '/');
|                 ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>