teamd: Re-adjust include header order
So it gets the library definition before kernel definition

usr/include/ne
tinet/if_ether.h:101:8: error: redefinition of 'struct ethhdr'
 struct ethhdr {
        ^~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>